name: Build check node app

on:
  workflow_call:
    inputs:
      NODE_VER:
        required: false
        type: string
        default: '18.x'

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: ${{ inputs.NODE_VER }}
      - name: Autentiser med GitHub NPM registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.READER_TOKEN }}" >> ~/.npmrc
          echo "@navikt:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - name: Install npm dependencies
        run: npm install
      - name: Build application
        run: npm run build
        env:
          IMAGE_PROXY_URL: 'Test'
          CDN_URL: 'Test'
          RUNTIME_ENVIRONMENT: 'Test'
      - name: Run linting
        run: npm run lint
