name: deploy-rollback

on:
  workflow_call:
    inputs:
      NAIS_RESOURCE:
        required: false
        type: string
        default: "nais.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "nais-prod.json"
      CLUSTER:
        required: false
        type: string
        default: 'dev-gcp'
      VERSION:
        required: false
        type: string
        default: "latest"

jobs:
  deploy-rollback:
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          VERSION: ${{ inputs.VERSION }}
        run: |
          echo "VERSION_TAG=$VERSION" >> $GITHUB_ENV
          echo "IMAGE=europe-north1-docker.pkg.dev/nais-management-233d/teamdigihot/$REPOSITORY_NAME:$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
        with:
          fetch-depth: 0
          ref: ${{ env.VERSION_TAG }}
      - uses: nais/deploy/actions/deploy@e79279e20795c1a03a92e8ae0bad4b770fd4e6d4 # v2
        name: deploy to ${{ inputs.CLUSTER }}
        env:
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}
